=== Engin1980/EFS-Extensions/Xmls/Xsds/AffinitySchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema id="Failures"
            targetNamespace="http://github.com/EFS-Extensions/xmls/affinity.xsd"
            elementFormDefault="qualified"
            xmlns="http://github.com/EFS-Extensions/xmls/affinity.xsd"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:g  ="http://github.com/EFS-Extensions/xmls/global.xsd"
>
  <xsd:import namespace="http://github.com/EFS-Extensions/xmls/global.xsd" schemaLocation="Global.xsd" />

  <xsd:element name="ruleBase">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="metaInfo" minOccurs="1" maxOccurs="1" type="g:metaData"/>
        <xsd:element name="affinity" minOccurs="0" maxOccurs="1" >
          <xsd:complexType>
            <xsd:sequence minOccurs="1" maxOccurs="unbounded">
              <xsd:element name="rule" type="affinityRule" />
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="priority" minOccurs="0" maxOccurs="1">
          <xsd:complexType>
            <xsd:sequence minOccurs="1" maxOccurs="unbounded">
              <xsd:element name="rule" type="priorityRule" />
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="resetIntervalInS" type="xsd:nonNegativeInteger" use="optional" default="0" />
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="affinityRule">
    <xsd:attribute name="title" type="g:nonemptyString" use="optional" />
    <xsd:attribute name="regex" type="g:nonemptyString" use="required" />
    <xsd:attribute name="roll" type="g:nonemptyString" use="required" />
  </xsd:complexType>

  <xsd:complexType name="priorityRule">
    <xsd:attribute name="title" type="g:nonemptyString" use="optional" />
    <xsd:attribute name="regex" type="g:nonemptyString" use="required" />
    <xsd:attribute name="priority" type="priorityLevel" use="required" />
  </xsd:complexType>

  <xsd:simpleType name="priorityLevel">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="Normal" />
      <xsd:enumeration value="AboveNormal" />
      <xsd:enumeration value="BelowNormal" />
      <xsd:enumeration value="High" />
      <xsd:enumeration value="Idle" />
      <xsd:enumeration value="RealTime" />
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>

=== Engin1980/EFS-Extensions/Xmls/Affinity/schema16threads.affi.xml
<?xml version="1.0" encoding="utf-8" ?>
<ruleBase
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://github.com/EFS-Extensions/xmls/affinity.xsd"
  xmlns:g  ="http://github.com/EFS-Extensions/xmls/global.xsd"
  xsi:noNamespaceSchemaLocation="file://./Xsds/AffinitySchema.xsd">
  <metaInfo>
    <g:label>Simple Affinity Schema</g:label>
    <g:author>Marek Vajgl</g:author>
    <g:description>
      Testing configuration
    </g:description>
  </metaInfo>
  <affinity>
    <rule title="AI Flow" regex="AIFlow.exe" roll="0-4" />
    <rule title="AI Ground" regex="AIGround.exe" roll="0-4" />
    <rule title="GSX - Couatl64" regex="Couatl64_MSFS.exe" roll="0-4" />
    <rule title="FBW SimBridge" regex="fbw-simbridge.exe" roll="0-4" />
    <rule title="FBW Installer" regex="FlyByWire.+" roll="0-4" />
    <rule title="FSLTL Traffic Injector" regex="fsltl-traficinjector.exe" roll="0-4" />
    <rule title="FSUIPC7" regex="fbw-FSUIPC7.exe" roll="0-4" />
    <rule title="Navigraph" regex="Navigraph Hub.exe" roll="0-4" />
    <rule title="PACX" regex="PACX.exe" roll="0-4" />
    <rule title="SimConnectServer" regex="SimConnectServer.exe" roll="0-4" />
    <rule title="SimConnectServer" regex="SimConnectServer.exe" roll="0-4" />
    <rule title="Steam" regex="^steam.+" roll="0-4" />
    <rule title="X-Touch-Mini-FS2020" regex="X-Touch-MINI-FS2020.exe" roll="0-4" />
    <rule title="FS2020" regex="FlightSimulator.exe" roll="4-12" />
    <rule title="(anything else)" regex=".+" roll="13-16" />
  </affinity>
  <priority>
    <rule title="FS2020" regex="FlightSimulator.exe" priority="High" />
  </priority>
</ruleBase>
