=== Engin1980/EFS-Extensions/Xmls/Xsds/ChecklistSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema id="Schema"
            targetNamespace="http://github.com/EFS-Extensions/xmls/checklists.xsd"
            elementFormDefault="qualified"
            xmlns="http://github.com/EFS-Extensions/xmls/checklists.xsd"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:g ="http://github.com/EFS-Extensions/xmls/global.xsd"
>
  <xsd:import namespace="http://github.com/EFS-Extensions/xmls/global.xsd" schemaLocation="Global.xsd" />

  <xsd:element name="checklistSet">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="meta" minOccurs="1" maxOccurs="1" type="g:metaData"/>
        <xsd:element name="properties" minOccurs="0" maxOccurs="1" type="g:simProperties" />
        <xsd:element name="checklist" minOccurs="1" maxOccurs="unbounded" type="checklist"/>
      </xsd:sequence>
      <xsd:attribute name="firstChecklistId" type="g:nonemptyString" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="checklist">
    <xsd:choice minOccurs="1" maxOccurs="unbounded">
      <xsd:element name="items" minOccurs="1" maxOccurs="1">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="item" minOccurs="1" maxOccurs="unbounded" type="item"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="variables" minOccurs="0" maxOccurs="1" type="g:variables" />
      <xsd:element name="trigger" minOccurs="0" maxOccurs="1" type="g:stateCheckConditionTop"/>      
      <xsd:element name="customEntrySpeech" minOccurs="0" maxOccurs="1" type="g:speech"/>
      <xsd:element name="customExitSpeech" minOccurs="0" maxOccurs="1" type="g:speech"/>
      <xsd:element name="customPausedAlertSpeech" minOccurs="0" maxOccurs="1" type="g:speech"/>
    </xsd:choice>
    <xsd:attribute name="id" type="g:nonemptyString" use="required"/>
    <xsd:attribute name="callSpeech" type="g:nonemptyString" use="optional"/>
    <xsd:attribute name="nextChecklistIds" type="checklistIds" use="optional"/>
  </xsd:complexType>

  <xsd:simpleType name="checklistIds">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="\S+(;\S+)*" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="nextChecklistId">
    <xsd:attribute name="id" type="g:nonemptyString" use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="item">
    <xsd:sequence>
      <xsd:element name="call" type="g:speech"/>
      <xsd:element name="confirmation" type="g:speech"/>
    </xsd:sequence>
  </xsd:complexType>

</xsd:schema>

=== Engin1980/EFS-Extensions/Xmls/Checklist/baron.checklist.xml
<?xml version="1.0" encoding="utf-8" ?>
<checklistSet
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://github.com/EFS-Extensions/xmls/checklists.xsd"
  xmlns:g="http://github.com/EFS-Extensions/xmls/global.xsd"
  xsi:noNamespaceSchemaLocation="file://./Xsds/ChecklistSchema.xsd"
  firstChecklistId="batteryOn">
  <meta>
    <g:label>Baron B58 checklist</g:label>
    <g:author>Marek Vajgl</g:author>
    <g:description>Simple checklists Baron B58 default plane</g:description>
  </meta>
  <checklist id="beforeStart" callSpeech="Before Start-up">
    <items>
      <item>
        <call type="speech" value="Parking Brake"/>
        <confirmation type="speech" value="Set"/>
      </item>
      <item>
        <call type="speech" value="Avionics"/>
        <confirmation type="speech" value="Off"/>
      </item>
      <item>
        <call type="speech" value="Landing Gear"/>
        <confirmation type="speech" value="Down"/>
      </item>
      <item>
        <call type="speech" value="Fuel Selectors"/>
        <confirmation type="speech" value="On"/>
      </item>
      <item>
        <call type="speech" value="Battery Switch"/>
        <confirmation type="speech" value="On"/>
      </item>
      <item>
        <call type="speech" value="Beacon Light"/>
        <confirmation type="speech" value="On"/>
      </item>
      <item>
        <call type="speech" value="Fuel Quantity"/>
        <confirmation type="speech" value="Checked"/>
      </item>
    </items>
    <trigger>
      <g:property name="beaconLight" direction="passingUp" expression="0.5"/>
    </trigger>
  </checklist>
  <checklist id="beforeTaxi" callSpeech="Before Taxi">
    <items>
      <item>
        <call type="speech" value="Alternator Switch"/>
        <confirmation type="speech" value="On"/>
      </item>
      <item>
        <call type="speech" value="Voltmeter"/>
        <confirmation type="speech" value="28 volts at least"/>
      </item>
      <item>
        <call type="speech" value="Avionics"/>
        <confirmation type="speech" value="On"/>
      </item>
      <item>
        <call type="speech" value="Exterior Lights"/>
        <confirmation type="speech" value="On"/>
      </item>
      <item>
        <call type="speech" value="Surfaces"/>
        <confirmation type="speech" value="Checked"/>
      </item>
      <item>
        <call type="speech" value="Trim"/>
        <confirmation type="speech" value="Set"/>
      </item>
      <item>
        <call type="speech" value="Flaps"/>
        <confirmation type="speech" value="Set"/>
      </item>
    </items>
    <trigger>
      <g:and>
        <g:property name="pushbackTugConnected" direction="below" expression="1" />
        <g:property name="engine1Running" direction="above" expression="0"/>
        <g:property name="engine2Running" direction="above" expression="0"/>
        <g:for seconds="3">
          <g:property name="parkingBrakeSet" direction="below" expression="1"/>
        </g:for>
      </g:and>
    </trigger>
  </checklist>
  <checklist id="beforeTakeoff" callSpeech="Before Take Off">
    <items>
      <item>
        <call type="speech" value="Seat Belts"/>
        <confirmation type="speech" value="On"/>
      </item>
      <item>
        <call type="speech" value="Mixture"/>
        <confirmation type="speech" value="Set"/>
      </item>
      <item>
        <call type="speech" value="Propeller"/>
        <confirmation type="speech" value="Feathering"/>
      </item>
      <item>
        <call type="speech" value="Fuel Boost Pump" />
        <confirmation type="speech" value="On" />
      </item>
      <item>
        <call type="speech" value="Landing Lights"/>
        <confirmation type="speech" value="On"/>
      </item>
      <item>
        <call type="speech" value="Strobe Light"/>
        <confirmation type="speech" value="On"/>
      </item>
      <item>
        <call type="speech" value="Transponder mode"/>
        <confirmation type="speech" value="Charlie"/>
      </item>
    </items>
  </checklist>
  <checklist id="afterTakeoff" callSpeech="After Take Off">
    <items>
      <item>
        <call type="speech" value="Gear" />
        <confirmation type="speech" value="Up" />
      </item>
      <item>
        <call type="speech" value="Landing Lights" />
        <confirmation type="speech" value="Off" />
      </item>
    </items>
    <trigger>
      <g:property name="height" direction="above" expression="400"/>
    </trigger>
  </checklist>
  <checklist id="departure" callSpeech="Departure">
    <items>
      <item>
        <call type="speech" value="Flaps" />
        <confirmation type="speech" value="Up" />
      </item>
      <item>
        <call type="speech" value="Fuel Boost Pump" />
        <confirmation type="speech" value="Off" />
      </item>
      <item>
        <call type="speech" value="Cowl Flaps" />
        <confirmation type="speech" value="Closed" />
      </item>
    </items>
    <trigger>
      <g:or>
        <g:property name="height" direction="above" expression="1500"/>
        <g:property name="ias" direction="above" expression="130"/>
      </g:or>
    </trigger>
  </checklist>
  <checklist id="descend" callSpeech="Descend">
    <items>
      <item>
        <call type="speech" value="Altimeter"/>
        <confirmation type="speech" value="Set"/>
      </item>
      <item>
        <call type="speech" value="Mixture"/>
        <confirmation type="speech" value="Set full"/>
      </item>
      <item>
        <call type="speech" value="Cowl flaps" />
        <confirmation type="speech" value="Closed" />
      </item>
      <item>
        <call type="speech" value="Reference speeds" />
        <confirmation type="speech" value="Set" />
      </item>
    </items>
    <trigger>
      <g:for seconds="60">
        <g:property name="vs" direction="below" expression="-1800"/>
      </g:for>
    </trigger>
  </checklist>
  <checklist id="approach" callSpeech="Approach" nextChecklistIds="shortFinal;goAround">
    <items>
      <item>
        <call type="speech" value="Flaps" />
        <confirmation type="speech" value="Set" />
      </item>
      <item>
        <call type="speech" value="Lights" />
        <confirmation type="speech" value="On" />
      </item>
      <item>
        <call type="speech" value="Seat Belts" />
        <confirmation type="speech" value="On" />
      </item>
    </items>
    <trigger>
      <g:and>
        <g:property name="ias" direction="below" expression="200"/>
        <g:property name="height" direction="below" expression="10000"/>
      </g:and>
    </trigger>
  </checklist>
  <checklist id="shortFinal" callSpeech="Short Final" nextChecklistIds="vacated;goAround">
    <items>
      <item>
        <call type="speech" value="Landing Gear" />
        <confirmation type="speech" value="Down Three Green" />
      </item>
      <item>
        <call type="speech" value="Flaps" />
        <confirmation type="speech" value="Full" />
      </item>
      <item>
        <call type="speech" value="Speed brake" />
        <confirmation type="speech" value="None" />
      </item>
      <item>
        <call type="speech" value="Landing Clearance" />
        <confirmation type="speech" value="Obtained" />
      </item>
    </items>
    <trigger>
      <g:and>
        <g:property name="ias" direction="below" expression="200"/>
        <g:property name="height" direction="below" expression="1000"/>
      </g:and>
    </trigger>
  </checklist>
  <checklist id="goAround" callSpeech="Go Around" nextChecklistIds="approach">
    <items>
      <item>
        <call type="speech" value="Gear"/>
        <confirmation type="speech" value="Up"/>
      </item>
      <item>
        <call type="speech" value="Flaps"/>
        <confirmation type="speech" value="Checked"/>
      </item>
    </items>
  </checklist>
  <checklist id="vacated" callSpeech="Vacated">
    <items>
      <item>
        <call type="speech" value="Speed Brakes" />
        <confirmation type="speech" value="Retracted" />
      </item>
      <item>
        <call type="speech" value="Flaps" />
        <confirmation type="speech" value="Up" />
      </item>
      <item>
        <call type="speech" value="Transponder" />
        <confirmation type="speech" value="Stand by" />
      </item>
      <item>
        <call type="speech" value="Lights" />
        <confirmation type="speech" value="Off" />
      </item>
    </items>
  </checklist>
</checklistSet>

=== Engin1980/EFS-Extensions/Xmls/Checklist/cj4.checklist.xml
<?xml version="1.0" encoding="utf-8" ?>
<checklistSet
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://github.com/EFS-Extensions/xmls/checklists.xsd"
  xmlns:g="http://github.com/EFS-Extensions/xmls/global.xsd"
  xsi:noNamespaceSchemaLocation="file://./Xsds/ChecklistSchema.xsd"
  firstChecklistId="batteryOn">
  <meta>
    <g:label>CJ4 checklist</g:label>
    <g:author>Marek Vajgl</g:author>
    <g:description>Simple checklists test for Working Title CJ4</g:description>
  </meta>
  <checklist id="beforeStart" callSpeech="Before Start-up">
    <items>
      <item>
        <call type="speech" value="Sim toolkit started"/>
        <confirmation type="speech" value="checked"/>
      </item>
      <item>
        <call type="speech" value="Navigraph started"/>
        <confirmation type="speech" value="checked"/>
      </item>
      <item>
        <call type="speech" value="Battery Switch"/>
        <confirmation type="speech" value="on"/>
      </item>
      <item>
        <call type="speech" value="Emergency Light Switch"/>
        <confirmation type="speech" value="on"/>
      </item>
      <item>
        <call type="speech" value="Standby Flight Display Switch"/>
        <confirmation type="speech" value="on"/>
      </item>
      <item>
        <call type="speech" value="Frequency"/>
        <confirmation type="speech" value="Set"/>
      </item>
      <item>
        <call type="speech" value="Squawk code"/>
        <confirmation type="speech" value="Set"/>
      </item>
      <item>
        <call type="speech" value="Parking Brake"/>
        <confirmation type="speech" value="Set"/>
      </item>
      <item>
        <call type="speech" value="Passenger Briefing"/>
        <confirmation type="speech" value="Started"/>
      </item>
      <item>
        <call type="speech" value="Seatbelts"/>
        <confirmation type="speech" value="On"/>
      </item>
      <item>
        <call type="speech" value="Climate Control"/>
        <confirmation type="speech" value="Off"/>
      </item>
      <item>
        <call type="speech" value="Beacon Light"/>
        <confirmation type="speech" value="On"/>
      </item>
      <item>
        <call type="speech" value="Throttles"/>
        <confirmation type="speech" value="Idle"/>
      </item>
    </items>
  </checklist>
  <checklist id="beforeTaxi" callSpeech="Before Taxi">
    <items>
      <item>
        <call type="speech" value="Avionics Switch"/>
        <confirmation type="speech" value="On"/>
      </item>
      <item>
        <call type="speech" value="Q N H"/>
        <confirmation type="speech" value="Set"/>
      </item>
      <item>
        <call type="speech" value="Altitude"/>
        <confirmation type="speech" value="Set"/>
      </item>
      <item>
        <call type="speech" value="Flaps" />
        <confirmation type="speech" value="Set" />
      </item>
      <item>
        <call type="speech" value="Speed brake" />
        <confirmation type="speech" value="None" />
      </item>
      <item>
        <call type="speech" value="Climate Control Selector"/>
        <confirmation type="speech" value="On"/>
      </item>
      <item>
        <call type="speech" value="Taxi Lights"/>
        <confirmation type="speech" value="On"/>
      </item>
    </items>
    <trigger>
      <g:and>
        <g:property name="pushbackTugConnected" direction="below" expression="1" />
        <g:property name="engine1Running" direction="above" expression="0"/>
        <g:property name="engine2Running" direction="above" expression="0"/>
        <g:for seconds="3">
          <g:property name="parkingBrakeSet" direction="below" expression="1"/>
        </g:for>
      </g:and>
    </trigger>
  </checklist>
  <checklist id="beforeTakeoff" callSpeech="Before Take Off">
    <items>
      <item>
        <call type="speech" value="Ice Protection System" />
        <confirmation type="speech" value="Check" />
      </item>
      <item>
        <call type="speech" value="Climate Control Selector" />
        <confirmation type="speech" value="Off" />
      </item>
      <item>
        <call type="speech" value="Pitot Heat" />
        <confirmation type="speech" value="On" />
      </item>
      <item>
        <call type="speech" value="Lights" />
        <confirmation type="speech" value="On" />
      </item>
      <item>
        <call type="speech" value="Squawk Mode" />
        <confirmation type="speech" value="Charlie" />
      </item>
      <item>
        <call type="speech" value="Toga" />
        <confirmation type="speech" value="Set" />
      </item>
    </items>
  </checklist>
  <checklist id="afterTakeoff" callSpeech="After Take Off">
    <items>
      <item>
        <call type="speech" value="Gear" />
        <confirmation type="speech" value="Up" />
      </item>
      <item>
        <call type="speech" value="Yaw damper" />
        <confirmation type="speech" value="On" />
      </item>
    </items>
    <trigger>
      <g:property name="height" direction="above" expression="400"/>
    </trigger>
  </checklist>
  <checklist id="departure" callSpeech="Departure">
    <items>
      <item>
        <call type="speech" value="Flaps" />
        <confirmation type="speech" value="Up" />
      </item>
      <item>
        <call type="speech" value="Climate Control" />
        <confirmation type="speech" value="On" />
      </item>
    </items>
    <trigger>
      <g:and>
        <g:property name="height" direction="above" expression="1500"/>
        <g:property name="ias" direction="above" expression="180"/>
      </g:and>
    </trigger>
  </checklist>
  <checklist id="descend" callSpeech="Descend">
    <items>
      <item>
        <call type="speech" value="Metar and Q N H" />
        <confirmation type="speech" value="Obtained" />
      </item>
      <item>
        <call type="speech" value="Arrival and approach"/>
        <confirmation type="speech" value="Set"/>
      </item>
      <item>
        <call type="speech" value="Decision height" />
        <confirmation type="speech" value="Set" />
      </item>
      <item>
        <call type="speech" value="Reference speeds" />
        <confirmation type="speech" value="Set" />
      </item>
    </items>
    <trigger>
      <g:and>
        <g:property name="alt" direction="below" expression="18000"/>
        <g:for seconds="60">
          <g:property name="vs" direction="below" expression="-900"/>
        </g:for>
      </g:and>
    </trigger>
  </checklist>
  <checklist id="approach" callSpeech="Approach" nextChecklistIds="shortFinal;goAround">
    <items>
      <item>
        <call type="speech" value="Flaps" />
        <confirmation type="speech" value="Set" />
      </item>
      <item>
        <call type="speech" value="Lights" />
        <confirmation type="speech" value="On" />
      </item>
      <item>
        <call type="speech" value="Seat Belts" />
        <confirmation type="speech" value="On" />
      </item>
    </items>
    <trigger>
      <g:and>
        <g:property name="ias" direction="below" expression="200"/>
        <g:property name="height" direction="below" expression="10000"/>
      </g:and>
    </trigger>
  </checklist>
  <checklist id="shortFinal" callSpeech="Short Final" nextChecklistIds="vacated;goAround">
    <items>
      <item>
        <call type="speech" value="Landing Gear" />
        <confirmation type="speech" value="Down Three Green" />
      </item>
      <item>
        <call type="speech" value="Flaps" />
        <confirmation type="speech" value="Full" />
      </item>
      <item>
        <call type="speech" value="Speed brake" />
        <confirmation type="speech" value="None" />
      </item>
      <item>
        <call type="speech" value="Landing Clearance" />
        <confirmation type="speech" value="Obtained" />
      </item>
    </items>
    <trigger>
      <g:and>
        <g:property name="ias" direction="below" expression="200"/>
        <g:property name="height" direction="below" expression="1000"/>
      </g:and>
    </trigger>
  </checklist>
  <checklist id="goAround" callSpeech="Go Around" nextChecklistIds="approach">
    <items>
      <item>
        <call type="speech" value="Gear"/>
        <confirmation type="speech" value="Up"/>
      </item>
      <item>
        <call type="speech" value="Flaps"/>
        <confirmation type="speech" value="Checked"/>
      </item>
    </items>
  </checklist>
  <checklist id="vacated" callSpeech="Vacated">
    <items>
      <item>
        <call type="speech" value="Speed Brakes" />
        <confirmation type="speech" value="Retracted" />
      </item>
      <item>
        <call type="speech" value="Flaps" />
        <confirmation type="speech" value="Up" />
      </item>
      <item>
        <call type="speech" value="Squawk" />
        <confirmation type="speech" value="Stand by" />
      </item>
      <item>
        <call type="speech" value="Lights" />
        <confirmation type="speech" value="Off" />
      </item>
    </items>
  </checklist>
</checklistSet>

=== Engin1980/EFS-Extensions/Xmls/Checklist/cessna172.checklist.xml
<?xml version="1.0" encoding="utf-8" ?>
<checklistSet
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://github.com/EFS-Extensions/xmls/checklists.xsd"
  xmlns:g="http://github.com/EFS-Extensions/xmls/global.xsd"
  xsi:noNamespaceSchemaLocation="file://./Xsds/ChecklistSchema.xsd"
  firstChecklistId="batteryOn">
  <meta>
    <g:label>Simple C172 checklist</g:label>
    <g:author>Marek Vajgl</g:author>
    <g:description>Simple checklists C172 default plane</g:description>
  </meta>
  <checklist id="beforeStart" callSpeech="Before Start-up">
    <items>
      <item>
        <call type="speech" value="Parking Brake"/>
        <confirmation type="speech" value="Set"/>
      </item>
      <item>
        <call type="speech" value="Avionics"/>
        <confirmation type="speech" value="Off"/>
      </item>
      <item>
        <call type="speech" value="Fuel Selectors"/>
        <confirmation type="speech" value="On"/>
      </item>
      <item>
        <call type="speech" value="Batery Switch"/>
        <confirmation type="speech" value="On"/>
      </item>
      <item>
        <call type="speech" value="Beacon Light"/>
        <confirmation type="speech" value="On"/>
      </item>
      <item>
        <call type="speech" value="Fuel Quantity"/>
        <confirmation type="speech" value="Checked"/>
      </item>
    </items>
    <trigger>
      <g:property name="beaconLight" direction="passingUp" expression="0.5"/>
    </trigger>
  </checklist>
  <checklist id="beforeTaxi" callSpeech="Before Taxi">
    <items>
      <item>
        <call type="speech" value="Alternator Switch"/>
        <confirmation type="speech" value="On"/>
      </item>
      <item>
        <call type="speech" value="Voltmeter"/>
        <confirmation type="speech" value="28 volts at least"/>
      </item>
      <item>
        <call type="speech" value="Avionics"/>
        <confirmation type="speech" value="On"/>
      </item>
      <item>
        <call type="speech" value="Exterior Lights"/>
        <confirmation type="speech" value="On"/>
      </item>
      <item>
        <call type="speech" value="Surfaces"/>
        <confirmation type="speech" value="Checked"/>
      </item>
      <item>
        <call type="speech" value="Trim"/>
        <confirmation type="speech" value="Set"/>
      </item>
      <item>
        <call type="speech" value="Flaps"/>
        <confirmation type="speech" value="Set"/>
      </item>
    </items>
    <trigger>
      <g:and>
        <g:property name="pushbackTugConnected" direction="below" expression="1" />
        <g:property name="engine1Running" direction="above" expression="0"/>
        <g:for seconds="3">
          <g:property name="parkingBrakeSet" direction="below" expression="1"/>
        </g:for>
      </g:and>
    </trigger>
  </checklist>
  <checklist id="beforeTakeoff" callSpeech="Before Take Off">
    <items>
      <item>
        <call type="speech" value="Mixture"/>
        <confirmation type="speech" value="Set"/>
      </item>
      <item>
        <call type="speech" value="Lights"/>
        <confirmation type="speech" value="Checked"/>
      </item>
      <item>
        <call type="speech" value="Transponder"/>
        <confirmation type="speech" value="On"/>
      </item>
    </items>
  </checklist>
  <checklist id="departure" callSpeech="Departure">
    <items>
      <item>
        <call type="speech" value="Flaps" />
        <confirmation type="speech" value="Up" />
      </item>
    </items>
    <trigger>
      <g:and>
        <g:property name="height" direction="above" expression="500"/>
      </g:and>
    </trigger>
  </checklist>
  <checklist id="shortFinal" callSpeech="Short Final" nextChecklistIds="vacated;goAround">
    <items>
      <item>
        <call type="speech" value="Flaps" />
        <confirmation type="speech" value="Set" />
      </item>
      <item>
        <call type="speech" value="Landing Clearance" />
        <confirmation type="speech" value="Obtained" />
      </item>
      <item>
        <call type="speech" value="Mixture"/>
        <confirmation type="speech" value="Set"/>
      </item>
      <item>
        <call type="speech" value="Lights"/>
        <confirmation type="speech" value="Checked"/>
      </item>
    </items>
    <trigger>
      <g:and>
        <g:property name="height" direction="below" expression="500"/>
      </g:and>
    </trigger>
  </checklist>
  <checklist id="goAround" callSpeech="Go Around" nextChecklistIds="shortFinal">
    <items>
      <item>
        <call type="speech" value="Flaps"/>
        <confirmation type="speech" value="Checked"/>
      </item>
    </items>
    <trigger>
      <g:property name="vs" direction="above" expression="500" />
    </trigger>
  </checklist>
  <checklist id="vacated" callSpeech="Vacated">
    <items>
      <item>
        <call type="speech" value="Flaps" />
        <confirmation type="speech" value="Up" />
      </item>
      <item>
        <call type="speech" value="Transponder" />
        <confirmation type="speech" value="Stand by" />
      </item>
      <item>
        <call type="speech" value="Lights" />
        <confirmation type="speech" value="Adjusted" />
      </item>
    </items>
  </checklist>
</checklistSet>
